# Pre-commit that runs locally
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '\.(yaml|yml)$'

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.4
    hooks:
      - id: check-model-has-description
        args: ["--manifest", "chapter_10/snowflakebook/target/manifest.json"]
      - id: check-model-has-tests-by-group
        args:
          [
            "--tests",
            "not_null",
            "--test-cnt",
            "1",
            "--manifest",
            "chapter_10/snowflakebook/target/manifest.json",
          ]
      - id: check-model-has-tests-by-group
        args:
          [
            "--tests",
            "unique",
            "unique_combination_of_columns",
            "--test-cnt",
            "1",
            "--manifest",
            "chapter_10/snowflakebook/target/manifest.json",
          ]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.1
    hooks:
      - id: sqlfluff-fix
        args:
          [
            --config,
            "chapter_10/snowflakebook/.sqlfluff",
            --show-lint-violations,
          ]
        additional_dependencies:
          ["dbt-core==1.8.7", "dbt-snowflake==1.8.3", "sqlfluff-templater-dbt"]
