
CREATE WAREHOUSE XSCOMPUTE
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300    -- Automatically suspend after 5 minutes of inactivity
    AUTO_RESUME = TRUE;   -- Automatically resume when queried

CREATE ROLE jumpstart_admin;

-- Switch to SECURITYADMIN or ACCOUNTADMIN role first
USE ROLE SECURITYADMIN;

-- Create the dbt user with password
CREATE USER dbt_user
    PASSWORD = 'YourStrongPassword123'  -- Replace with a secure password
    DEFAULT_ROLE = jumpstart_admin
    DEFAULT_WAREHOUSE = XSCOMPUTE;

-- Grant the jumpstart_admin role to the user
GRANT ROLE jumpstart_admin TO USER dbt_user;

CREATE DATABASE JUMPSTART;

-- Create the required schemas
CREATE SCHEMA JUMPSTART.STG;
CREATE SCHEMA JUMPSTART.BUSINESS;

GRANT OPERATE ON WAREHOUSE XSCOMPUTE TO ROLE jumpstart_admin;
GRANT USAGE ON WAREHOUSE XSCOMPUTE TO ROLE jumpstart_admin;

-- 5. Grant database privileges
GRANT USAGE ON DATABASE JUMPSTART TO ROLE jumpstart_admin;
GRANT CREATE SCHEMA ON DATABASE JUMPSTART TO ROLE jumpstart_admin;
GRANT MODIFY ON DATABASE JUMPSTART TO ROLE jumpstart_admin;

-- 6. Grant schema privileges
GRANT USAGE ON SCHEMA JUMPSTART.STG TO ROLE jumpstart_admin;
GRANT CREATE TABLE ON SCHEMA JUMPSTART.STG TO ROLE jumpstart_admin;
GRANT CREATE VIEW ON SCHEMA JUMPSTART.STG TO ROLE jumpstart_admin;
GRANT MODIFY ON SCHEMA JUMPSTART.STG TO ROLE jumpstart_admin;
GRANT SELECT ON ALL TABLES IN SCHEMA JUMPSTART.STG TO ROLE jumpstart_admin;
GRANT SELECT ON FUTURE TABLES IN SCHEMA JUMPSTART.STG TO ROLE jumpstart_admin;

GRANT USAGE ON SCHEMA JUMPSTART.BUSINESS TO ROLE jumpstart_admin;
GRANT CREATE TABLE ON SCHEMA JUMPSTART.BUSINESS TO ROLE jumpstart_admin;
GRANT CREATE VIEW ON SCHEMA JUMPSTART.BUSINESS TO ROLE jumpstart_admin;
GRANT MODIFY ON SCHEMA JUMPSTART.BUSINESS TO ROLE jumpstart_admin;
GRANT SELECT ON ALL TABLES IN SCHEMA JUMPSTART.BUSINESS TO ROLE jumpstart_admin;
GRANT SELECT ON FUTURE TABLES IN SCHEMA JUMPSTART.BUSINESS TO ROLE jumpstart_admin;

-- 7. Grant access to SNOWFLAKE_SAMPLE_DATA
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE jumpstart_admin;

-- assign role to your user
GRANT ROLE jumpstart_admin TO USER <YOUR USER>;
USE ROLE jumpstart_admin;


-- 8. Grant specific access to TPCH_SF1 schema
GRANT USAGE ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE jumpstart_admin;
GRANT USAGE ON SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE jumpstart_admin;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE jumpstart_admin;

--9. Switch to the new warehouse
USE WAREHOUSE XSCOMPUTE;

--10. Test the access
select * from
SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
