version: 2

models:
  - name: dim_customer
    description: "Customer dimension table with detailed customer and geographic information"
    columns:
      - name: customer_key
        description: "Primary key for the customer"
        tests:
          - unique
          - not_null
      - name: market_segment
        description: "Market segment of the customer"
        tests:
          - not_null
          - accepted_values:
              values:
                [
                  "AUTOMOBILE",
                  "BUILDING",
                  "FURNITURE",
                  "MACHINERY",
                  "HOUSEHOLD",
                ]
      - name: nation_name
        description: "Name of the customer's nation"
        tests:
          - not_null
      - name: region_name
        description: "Name of the customer's region"
        tests:
          - not_null
          - accepted_values:
              values: ["AFRICA", "AMERICA", "ASIA", "EUROPE", "MIDDLE EAST"]

  - name: dim_product
    description: "Product dimension table with product details"
    columns:
      - name: product_key
        description: "Primary key for the product"
        tests:
          - unique
          - not_null
      - name: manufacturer
        description: "Manufacturer of the product"
        tests:
          - not_null
      - name: retail_price
        description: "Retail price of the product"
        tests:
          - not_null

  - name: fact_orders
    description: "Fact table capturing order and line item details"
    columns:
      - name: order_key
        description: "Primary key for the order"
        tests:
          - unique
          - not_null
      - name: customer_key
        description: "Foreign key to the customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: product_key
        description: "Foreign key to the product dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: final_price
        description: "Final price after discounts and taxes"
        tests:
          - not_null
