version: 2

sources:
  - name: tpch
    description: "TPC-H Sample Dataset from Snowflake"
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        description: "Customer information including demographics and location"
        columns:
          - name: c_custkey
            description: "Primary key for customer"
            tests:
              - unique
              - not_null
          - name: c_name
            description: "Customer name"
            tests:
              - not_null
          - name: c_nationkey
            description: "Foreign key to nation table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'nation')
                  field: n_nationkey
          - name: c_mktsegment
            description: "Market segment of the customer"
            tests:
              - not_null
              - accepted_values:
                  values:
                    [
                      "AUTOMOBILE",
                      "BUILDING",
                      "FURNITURE",
                      "MACHINERY",
                      "HOUSEHOLD",
                    ]

      - name: lineitem
        description: "Detailed line items for each order"
        columns:
          - name: l_orderkey
            description: "Foreign key to orders table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'orders')
                  field: o_orderkey
          - name: l_partkey
            description: "Foreign key to part table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'part')
                  field: p_partkey
          - name: l_suppkey
            description: "Foreign key to supplier table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'supplier')
                  field: s_suppkey
          - name: l_quantity
            description: "Quantity ordered"
            tests:
              - not_null

          - name: l_extendedprice
            description: "Line item extended price"
            tests:
              - not_null

      - name: nation
        description: "Reference table for nations"
        columns:
          - name: n_nationkey
            description: "Primary key for nation"
            tests:
              - unique
              - not_null
          - name: n_name
            description: "Nation name"
            tests:
              - unique
              - not_null
          - name: n_regionkey
            description: "Foreign key to region table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'region')
                  field: r_regionkey

      - name: orders
        description: "Order header information"
        columns:
          - name: o_orderkey
            description: "Primary key for orders"
            tests:
              - unique
              - not_null
          - name: o_custkey
            description: "Foreign key to customer table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'customer')
                  field: c_custkey
          - name: o_orderdate
            description: "Date when order was placed"
            tests:
              - not_null
          - name: o_orderstatus
            description: "Current status of the order"
            tests:
              - accepted_values:
                  values: ["O", "F", "P"]

      - name: part
        description: "Product/part information"
        columns:
          - name: p_partkey
            description: "Primary key for part"
            tests:
              - unique
              - not_null
          - name: p_name
            description: "Part name"
            tests:
              - not_null
          - name: p_mfgr
            description: "Manufacturer"
            tests:
              - not_null
          - name: p_brand
            description: "Brand of the part"
            tests:
              - not_null
          - name: p_retailprice
            description: "Suggested retail price"
            tests:
              - not_null

      - name: region
        description: "Reference table for regions"
        columns:
          - name: r_regionkey
            description: "Primary key for region"
            tests:
              - unique
              - not_null
          - name: r_name
            description: "Region name"
            tests:
              - unique
              - not_null
              - accepted_values:
                  values: ["AFRICA", "AMERICA", "ASIA", "EUROPE", "MIDDLE EAST"]

      - name: supplier
        description: "Supplier information"
        columns:
          - name: s_suppkey
            description: "Primary key for supplier"
            tests:
              - unique
              - not_null
          - name: s_name
            description: "Supplier name"
            tests:
              - not_null
          - name: s_nationkey
            description: "Foreign key to nation table"
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'nation')
                  field: n_nationkey
